### ISSUE TITLE
MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)[Bug]: <Choose an appropriate title>

### ISSUE THREAD

**Issue by mjmagin** [ThexXTURBOXx/flutter_web_auth_2#102]
### Description

Hi I get this error when calling the authenticate method is a flutter web app hosted on firebase. 

"MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)"

This works fine when I run the app locally on my laptop but not when it is hosted. The url i pass to the FlutterWebAuth2.authenticate works correctly when I manually paste into a browser.

Any help much appreciated.

### Minimal Reproduction

final result = await FlutterWebAuth2.authenticate(
                          url: updatedUrl, callbackUrlScheme: "my-app");

This is in a flutter web app hosted on firebase. The url works correctly when manually pasted into a browser and also works correctly when run locally.

### Exception or Error

MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)

### Expected Behaviour

I expect the authenticate method to open a google oauth2 consent url 

### Device

desktop

### OS

mac OS 14.2.1 (23C71)

### Browser

chrome and safari

### Flutter version

3.19.0

### flutter_web_auth_2 version

3.1.1

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Could you maybe try the latest `4.x` beta version? If that also does not work, I will investigate a bit more

**Comment by mjmagin** [comment]
Thanks for your response - I managed to fix this by doing a flutter clean and rebuild of the app and deploying again on v3.1.1 Apologies - I should have done this before raising the issue. Many Thanks

**Comment by ThexXTURBOXx** [comment]
No problem, and thank you for reporting back! :)
