### ISSUE TITLE
[Bug]: ClearAllDanglingCalls onResume in web app after upgrading to flutter 3.22.0 

### ISSUE THREAD

**Issue by uberchilly** [ThexXTURBOXx/flutter_web_auth_2#108]
### Description

After upgrading to flutter 3.22.0 in my flutter web app on each resume I get bombarded with lots and lots of logs `clearAllDanglingCalls`

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Upgrade to flutter 3.22.0
2. Run minimal flutter app with auth library on web

### Exception or Error

```
Uncaught (in promise) InternalError: too much recursion
packages/flutter_web_auth_2_platform_interface/flutter_web_auth_2_platform_interface.dart 38:47  clearAllDanglingCalls
packages/flutter_web_auth_2/flutter_web_auth_2.dart 88:21                                        _cleanUpDanglingCalls
```

### Expected Behaviour

To work like it does with flutter 3.19.6

### Device

Desktop Computer

### OS

Windows 11

### Browser

Chrome

### Flutter version

3.22.0

### flutter_web_auth_2 version

3.1.1

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by Sernrbia** [comment]
I have the same issue

**Comment by ThexXTURBOXx** [comment]
Sorry - I did not even get notified about the 3.22.0 release. Will fix ASAP and release a fixed 3.x version. The same fix will be applied in the 4.x pre-releases as well.

**Comment by ThexXTURBOXx** [comment]
It is a very interesting issue... I don't know why it actually worked flawlessly in `3.19.x` - it should have caused this problem from the beginning, but I am glad it didn't!
I will push the new update in a minute as version `3.1.2`.

**Comment by ThexXTURBOXx** [comment]
The new version has been published. I will close this issue. If it still persists (for some reason), I will probably need a bit more information

**Comment by ThexXTURBOXx** [comment]
Thanks for the feedback, perfect! :)
