### ISSUE TITLE
[flutter_web_auth_2] iOS15.5 [AuthenticationSession] The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".

### ISSUE THREAD

**Issue by niumj** [ThexXTURBOXx/flutter_web_auth_2#11]
## Describe the bug
[flutter_web_auth_2] on iOS15.5 Exception: [AuthenticationSession] The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".

## To Reproduce
example code with calbackurlscheme[com.xxxx://logincalback]

## Device (please complete the following information!)
 - Device: Simulator iPhon13 Pro
 - OS: iOS15.5
 - Browser: Safari
 - `flutter_web_auth_2` version: 1.1.2

## Additional context
on iOS14 ,without the error, but auth0 authorize page is always loading !

**Comment by ThexXTURBOXx** [comment]
This is a limitation of iOS and it seems like I cannot do anything against it.
Further information can be found here:
https://developer.apple.com/forums/thread/679251
https://github.com/auth0-samples/auth0-react-native-sample/issues/45
