### ISSUE TITLE
[Bug]: The browser window cannot close properly after logging in success on the Android physical device

### ISSUE THREAD

**Issue by imwilliamxy** [ThexXTURBOXx/flutter_web_auth_2#113]
### Description

After successfully logging into the app, the browser window cannot be closed properly on Android devices. According to the logs, the app has already obtained the accessToken. The same operation works perfectly on iOS.

```
final result = await FlutterWebAuth2.authenticate(url: authUrl.toString(), callbackUrlScheme: "com.company.appname", options: const FlutterWebAuth2Options(intentFlags: ephemeralIntentFlags));
```

Similar links are here.
https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/106

according this thread, flutter_web_auth_2  was upgraded to version ^4.0.0-alpha.0

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
    final result = await FlutterWebAuth2.authenticate(url: authUrl.toString(), callbackUrlScheme: "com.company.appname", options: const FlutterWebAuth2Options(intentFlags: ephemeralIntentFlags));
    ```
2. The following code was added to AndroidManifest.xml
```
<activity
      android:name="com.linusu.flutter_web_auth_2.CallbackActivity"
      android:exported="true">
      <intent-filter android:label="App Login">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="ccom.company.appname"/>
      </intent-filter>
    </activity>
```

### Exception or Error

There's no error log

### Expected Behaviour

The web browser should close and app should come into focus

### Additional context

flutter doctor -v
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale en-US)
    • Flutter version 3.22.1 on channel stable at /Users/username/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/username/Documents/development/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/username/Documents/development/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version unknown)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0
    ✗ Unable to determine VS Code version.

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • Pixel 6a (mobile)    • codemasked            • android-arm64  • Android 14 (API 34)
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 125.0.6422.142

### Device

pixel 6a

### OS

Android 14

### Browser

Chrome

### Flutter version

Flutter version 3.22.1

### flutter_web_auth_2 version

^4.0.0-alpha.0

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Your `AndroidManifest.xml` contains `<data android:scheme="ccom.company.appname"/>` (note the `ccom` instead of `com`).

**Comment by imwilliamxy** [comment]
Thank you for your reply. The error you pointed out was due to my typo. 
When submitting this issue, for privacy reasons, I replaced the actual schema with ccom.company.appname. 
In the real production environment, the scheme included in the AndroidManifest.xml and the callbackUrlScheme parameter in the login code are exactly the same. I can confirm this for sure.

Thank you again for your quick response.

**Comment by ThexXTURBOXx** [comment]
Oh okay, sorry, should have known that...
Could you maybe try fixing the version of `flutter_web_auth_2` to `4.0.0-alpha.5` or to `4.0.0-alpha.4` and report back?
It might be that either version 6 or 5 contains code that breaks some stuff on Android... Could also be an Android 14 issue, but I tought I had tested this before

**Comment by tmarkovski** [comment]
I am experiencing the same issue. I made a short video of my setup, very basic app with a custom scheme configured. I've tried multiple versions of the 4.0.0-alpha.X, they all have the same behavior.

[Flutter App Custom Scheme Setup - Watch Video](https://www.loom.com/share/b2ebc6de5490466580fecd2b829232e0)

**Comment by ThexXTURBOXx** [comment]
@tmarkovski Thank you very much for the video - this is one of the most helpful bug reports I have ever received :)
I will take a closer look at this. On the first button push it looked like it actually redirected to the app, but for some reason went back again (the small flicker indicates something like that)... Let's see

**Comment by tmarkovski** [comment]
That's correct, it seems like it navigates back, but the custom tab is still there. Either way, the app is launched correctly and the result is returned by the `authenticate` function.

**Comment by joaquingrech** [comment]
anyone figured this out? I'm having the same issue on android device, after login the activity screen does not go away

**Comment by ThexXTURBOXx** [comment]
I'm sorry that I have not yet been able to look at it properly. I will update you once I had time to investigate

**Comment by irfan512** [comment]
@ThexXTURBOXx Hi i am facing same issue after login the activity screen does not go away

**Comment by ThexXTURBOXx** [comment]
@irfan512 I am aware of the issue :)

**Comment by joaquingrech** [comment]
To add more information, it only happens on a physical Android device. On the emulator, it works without issue.

**Comment by irfan512** [comment]
@joaquingrech on a physical Android device it come back in app

**Comment by joaquingrech** [comment]
I think I found the issue. Can you paste your androidmanifest? the launch mode of your main activity? It seems it must be set to singleTop. Mine was set to singleInstance and when I switched to singleTop it began working.

How's yours?

**Comment by ThexXTURBOXx** [comment]
@joaquingrech Mine is also set to `singleTop` and works fine - could indeed be the root of the problem!

**Comment by joaquingrech** [comment]
I'm not sure why it would fail and I believe mine was set to singleInstance by some other plugin. In theory, that should not make this plugin fail unless it's creating multiple instances and overlapping each other. You may want to try with the different launch modes and see which ones work and which ones fail to add it to the documentation (or fix if possible).

**Comment by irfan512** [comment]
@joaquingrech can you please paste your androidmanifest. 
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application
        android:name="${applicationName}"
        android:label="INGAGE"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">

        
        <meta-data
           android:name="com.facebook.sdk.ApplicationId"
           android:value="@string/facebook_app_id" />
        <meta-data 
           android:name="com.facebook.sdk.ClientToken" 
           android:value="@string/facebook_client_token"/>
        
        
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme" />

            
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            
            
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="ingage" android:host="callback" />
            </intent-filter>
        </activity>

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by ThexXTURBOXx** [comment]
@irfan512 You have a different issue: You have not read `flutter_web_auth_2`'s setup instructions.

**Comment by joaquingrech** [comment]
so what do we do about this? The temporary fix is to use singleTop and document it on the instructions. But I don't see why it should be enforced to singleTop

**Comment by ThexXTURBOXx** [comment]
@joaquingrech Since I am unable to reproduce the issue on my app, I can't really do anything against it currently.
I am open to PRs, though, of course.

**Comment by bekirtaskin** [comment]
I have the same issue. I am using keycloak, tab not closing but code and token works fine at the backgroud. If session is already available in Keycloak, without asking username and password keycloak retuns code and tab closing by itself as expected.

**Comment by ThreeSpinningAxes** [comment]
Been trying to solve this issue but nothing. @tmarkovski do you have any updates if you resolved the problem?

**Comment by feeza10250** [comment]
const html = '''
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Grant Access to Flutter</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    html, body { margin: 0; padding: 0; }

    main {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
    }

    #icon {
      font-size: 96pt;
    }

    #text {
      padding: 2em;
      max-width: 260px;
      text-align: center;
    }

    #button a {
      display: inline-block;
      padding: 6px 12px;
      color: white;
      border: 1px solid rgba(27,31,35,.2);
      border-radius: 3px;
      background-image: linear-gradient(-180deg, #34d058 0%, #22863a 90%);
      text-decoration: none;
      font-size: 14px;
      font-weight: 600;
    }

    #button a:active {
      background-color: #279f43;
      background-image: none;
    }
  </style>
</head>
<body>
  <main>
    <div id="icon">&#x1F3C7;</div>
    <div id="text">Press the button below to sign in using your localhost account.</div>
    <div id="button"><a href="CALLBACK_URL_HERE" onclick="goTo()">Sign in</a></div>
  </main>
</body>
<script>
function goTo(){
window.close()
}
</script>
</html>
''';


- add function 

<script>
function goTo(){
window.close()
}
</script>

- add onclick  
 <div id="button"><a href="CALLBACK_URL_HERE" onclick="goTo()">Sign in</a></div>

**Comment by nipzu** [comment]
This seems to be related to task affinity. I had `android:taskAffinity=””` set for my main activity in AndroidManifest.xml. Removing it fixed the issue.

**Comment by ThreeSpinningAxes** [comment]
> This seems to be related to task affinity. I had `android:taskAffinity=””` set for my main activity in AndroidManifest.xml. Removing it fixed the issue.

Can confirm this worked for me

**Comment by NilouMinooei** [comment]
I have this similar issue that in the android, web instance is not closed completely even with  `intentFlags: ephemeralIntentFlags `
so the session will always be active. I'm using it for the login process, so if you log out there is no way to login with different account (if you want)
The only way possible is to not use  `intentFlags: ephemeralIntentFlags ` and close the instance manually. Then it's definitely closed.
This issue started after updating flutter to 3.22 (which I suspect might be the issue)

**Comment by ThexXTURBOXx** [comment]
@NilouMinooei Please test whether removing the `android:taskAffinity` setting works for you.
This seems to be added in newer Flutter releases.

**Comment by NilouMinooei** [comment]
> @NilouMinooei Please test whether removing the `android:taskAffinity` setting works for you. This seems to be added in newer Flutter releases.

thank you for the reply @ThexXTURBOXx. I already checked it in the project. It does not exist even by accident :D

**Comment by ThexXTURBOXx** [comment]
Maybe some package adds it afterwards? Could you maybe check the `AndroidManifest.xml` extracted from the final APK file?

**Comment by NilouMinooei** [comment]
> Maybe some package adds it afterwards? Could you maybe check the `AndroidManifest.xml` extracted from the final APK file?

I can confirm that `android:taskAffinity` does not exist in extracted `AndroidManifest.xml` from final apk.

**Comment by Shiba-Kar** [comment]
> @tmarkovski Thank you very much for the video - this is one of the most helpful bug reports I have ever received :) I will take a closer look at this. On the first button push it looked like it actually redirected to the app, but for some reason went back again (the small flicker indicates something like that)... Let's see

The package [appwrite](https://github.com/appwrite/sdk-for-flutter/blob/f40d4cbbaa767cfffa60b72b95f467fc4fcbc21f/lib/src/client_io.dart#L333) depends on this , flutter_web_auth_2 works fine when there is only one google account somehow when there is multiple google accounts the browser does not close , but in the background the app is authenticated !!!

**Comment by Shiba-Kar** [comment]
> This seems to be related to task affinity. I had `android:taskAffinity=””` set for my main activity in AndroidManifest.xml. Removing it fixed the issue.

+1

**Comment by Bohdandn** [comment]
I recently updated to flutter 3.24.0 and updated most of ./android files from fresh template, it added `android:taskAffinity=””`. Issue reproduced on physical Android 14 and emulated Android 11 with Google, Apple and Facebook login. Removing `android:taskAffinity=””` solved the issue.

**Comment by zkrige** [comment]
Confirmed removing `android:taskAffinity=""` from manifest.xml fixed the issue for me

**Comment by ThexXTURBOXx** [comment]
I have added this to the instructions - no need for more duplicates here :)

**Comment by avinashk369** [comment]
> This seems to be related to task affinity. I had `android:taskAffinity=””` set for my main activity in AndroidManifest.xml. Removing it fixed the issue.

this configuration is fix for authorisation in browser but when if it is native app for authorisation it doesn't help. like if i authorise user for twitter using native twitter app then i am not able to close the auth screen after getting the token.

**Comment by contfedorov** [comment]
@ThexXTURBOXx @nipzu 

Looks like removing `android:taskAffinity=""` leads to vulnerability problem in application. Please find [this issue](https://github.com/flutter/flutter/issues/63559) in Flutter repo with explanation. 

Shortly:
- Problem with task affinity is fundamental bug in Android
- Removing `android:taskAffinity` attribute makes app vulnerable to [StrandHogg Attack](https://developer.android.com/privacy-and-security/risks/strandhogg)
- Flutter guys have intentionally set this attribute to empty string in initial app template
- Accroding to [Android docs](https://developer.android.com/privacy-and-security/risks/strandhogg), it can be mitigated by setting `android:minSdkVersion="30"`

So, workaround described [above](https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/113#issuecomment-2210791900) can be dangerous if you support Android prior to 11.

Is it possible to close browser window in any other way? Maybe, via any native calls to Kotlin/Java code?
