### ISSUE TITLE
[Bug]: <Broken redirect>

### ISSUE THREAD

**Issue by Jesse-Abruzzo** [ThexXTURBOXx/flutter_web_auth_2#116]
### Description

I havent changed my code for awhile and everything has been working fine. as soon as i updated this package to 3.1.2 and flutter to 3.22 the redirect stopped working. It goes to the html page but never redirects back to the org tab like it always did.

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
     final result = await FlutterWebAuth2.authenticate(url: url1String, callbackUrlScheme: 'https');
     final code = Uri.parse(result).queryParameters['code'];
    ```
2. It normaly would come back to the tab and then parse the code out. this was working fine for months. updated the package and flutter version and it doesnt come back. wont redirect back from my html page.

### Exception or Error

No visible error messages

### Expected Behaviour

redirect properly

### Device

Flutter web

### OS

Windows 12

### Browser

Chrome, EDGE

### Flutter version

3.22

### flutter_web_auth_2 version

3.1.2

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Please fill in all the fields

**Comment by Jesse-Abruzzo** [comment]
What else do you need to know specifically?

**Comment by Jesse-Abruzzo** [comment]
actually i see this error in the console from chrome: logindirect.html?code=codehere 

 Uncaught TypeError: Cannot read properties of null (reading 'postMessage')
    at logindirect.html?code=codehere

**Comment by Jesse-Abruzzo** [comment]
So i downgraded to version 2.1.4 and it works again. it was the upgrade that broke something. Can you please check that out.

**Comment by ThexXTURBOXx** [comment]
When upgrading to 3.x, have you applied the current version of the `Web` setup [like this](https://github.com/ThexXTURBOXx/flutter_web_auth_2/tree/3.x?tab=readme-ov-file#web)?

**Comment by Jesse-Abruzzo** [comment]
That was it. Thank you. Needed the new web setup. Didnt know that changed with the new version. thank you

**Comment by ThexXTURBOXx** [comment]
You're welcome :)
For the 4.x versions, the Web setup should be the same, by the way (if you want to test it out)
