### ISSUE TITLE
[Bug]: Provide an example for constructing valid callback url for windows and linux systems

### ISSUE THREAD

**Issue by ChManasa07** [ThexXTURBOXx/flutter_web_auth_2#124]
### Description

Currently, I am trying to implement a flutter desktop, android and iOS app for OAuth using custom redirect uri. The app is successfully navigating to Auth provider and authenticating there but never comes back to the flutter application.

In the Flutter desktop application, before leaving to auth provider, I am trying to create a local server with the port that my system is not listening to. like: http://localhost:62145/, but still the auth provider never comes back to the original flutter application. 

### Minimal Reproduction

Steps to reproduce the behaviour:

final result = await FlutterWebAuth2.authenticate(url: "", callbackUrlScheme: "http://localhost:62149/");

### Exception or Error

Auth provider never returns.

### Expected Behaviour

It should return a success or failure message back to the app.

### Device

Windows, Samsung Tablet.

### OS

windows OS 10

### Browser

Edge

### Flutter version

3.19.4

### flutter_web_auth_2 version

3.1.2

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Please try out the `4.x` pre releases

**Comment by ChManasa07** [comment]
I have tried with 4.x as well, it stil remains same.

**Comment by ThexXTURBOXx** [comment]
For `4.x`, make sure to follow [the migration guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2/tree/master?tab=readme-ov-file#upgrading-to-4x), also.
Please also try out the example on your machine. If that works fine, the problem is in your setup and not within the package.

**Comment by ThexXTURBOXx** [comment]
I consider this solved, I think.
