### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Sesa1988** [ThexXTURBOXx/flutter_web_auth_2#14]
Hi,

does this plugin support Windows? 
Its tagged with windows but there is nothing about windows in the readme/description at pub.dev

It would be nice if it does because its pain to handle it :)

**Comment by ThexXTURBOXx** [comment]
Hi, yes, Windows is somehow supported (see the example implementation for reference).
However, I do not like the way it works right now.
For more information on this, see other issues in this very repo here (some are already closed) :)
