### ISSUE TITLE
[Bug]: Discord login : Redirect URI is not supported by client.

### ISSUE THREAD

**Issue by tkddbf7348** [ThexXTURBOXx/flutter_web_auth_2#141]
I solved it by using this parameter additionally. 
You don't have to pay attention. 
If there are any additional issues, I will open the issue again then. Thank you!!

```
'code_challenge': codeChallenge,
'code_challenge_method': 'S256',
```

```
String codeVerifier = generateCodeVerifier();
String codeChallenge = generateCodeChallenge(codeVerifier);

 String generateCodeVerifier() {
    const String charset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';
    return List.generate(128, (i) => charset[Random.secure().nextInt(charset.length)]).join();
  }

  String generateCodeChallenge(String codeVerifier) {
    var bytes = ascii.encode(codeVerifier);
    var digest = sha256.convert(bytes);
    String codeChallenge = base64Url.encode(digest.bytes).replaceAll("=", "").replaceAll("+", "-").replaceAll("/", "_");
    return codeChallenge;
  }

```

### Description

This code is the content of my AndroidManifest file.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="CAM"
        android:name="${applicationName}"
        android:usesCleartextTraffic="true"
        android:largeHeap="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:enableOnBackInvokedCallback="true">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity 
            android:name="com.linusu.flutter_web_auth_2.CallbackActivity"
            android:exported="true">
            <intent-filter android:label="flutter_web_auth_2">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="camwebviewflutter" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/plain" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

```

And the authenticate function call part.
![image](https://github.com/user-attachments/assets/8ef5ff08-8b3e-45ca-b956-b053a94be784)
![image](https://github.com/user-attachments/assets/1c95e577-85e3-450e-8da0-2f19f22f3cc4)
![image](https://github.com/user-attachments/assets/212c1615-8f23-4941-974f-142bccc144b9)

+)
```
  options: const FlutterWebAuth2Options(useWebview: false)
```
is not working too..!

This is configuration in discord web.
![image](https://github.com/user-attachments/assets/b878525c-1170-4b52-bafd-dc510de0f32e)

I'm using version 4.0.1 of library in version 3.22.0 of flutter.

If I ask for authentication in this state, see the "Redirect URI ~~ is not supported by client."

Could you please check if there are any parts that I missed the settings or if there are any other parts that are wrong?

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
    <Paste your code here>
    ```
2. [...]

### Exception or Error

"Redirect URI is not supported by client." on discord.

### Expected Behaviour

redirecting to my app

### Screenshots

![Screenshot_20241024_114847_Chrome](https://github.com/user-attachments/assets/2abb4d12-721d-4fba-a3cd-d627dea7d797)
![Screenshot_20241024_114858_Chrome](https://github.com/user-attachments/assets/3245e998-f5eb-419f-b073-ed718dedb627)

### Additional context

fvm flutter doctor -v
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.4317], locale ko-KR)
    • Flutter version 3.22.0 on channel stable at C:\Users\sangyul\fvm\versions\3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\sangyul\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.7.34024.191
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\sangyul\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (4 available)
    • SM G991N (mobile) • 192.168.219.43:42143 • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows              • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 130.0.6723.60
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 128.0.2739.54

[√] Network resources
    • All expected network resources are available.

### Device

Samsung Galuxy S21

### OS

Android 14, One UI 6.1

### Browser

Chrome

### Flutter version

3.22.0

### flutter_web_auth_2 version

4.0.1

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by tkddbf7348** [comment]
> [@tkddbf7348](https://github.com/tkddbf7348) Hi Could you describe how did you solve this issue in details? I stuck with the same... Thanks!

I explained it at the top!

**Comment by NikonovichN** [comment]
@tkddbf7348 
Do you mean these two parameters in request?
```
'code_challenge': codeChallenge,
'code_challenge_method': 'S256',
```
