### ISSUE TITLE
[Bug]: IOS Error MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)

### ISSUE THREAD

**Issue by hungdt2nf** [ThexXTURBOXx/flutter_web_auth_2#145]
### Description

Hi.
My redicrect URL is custom sheme: <mycustomscheme>://callback
It is not https.
I tested it on Android device and it works fine.

But when I run it on IOS device, the following error appears:
MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)
I'm not sure if I'm missing any config.

### Minimal Reproduction

Steps to reproduce the behaviour:
1. Use the following code:
    ```dart
    final result = await FlutterWebAuth2.authenticate(
                url: state.url,
                callbackUrlScheme: '<mycustomscheme>',
              );
    ```
2. Just call function in step 1.

### Exception or Error

MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)

### Expected Behaviour

Open brower

### Device

Iphone 11

### OS

IOS 16.6.1

### Browser

Chrome

### Flutter version

3.24.5

### flutter_web_auth_2 version

4.0.2

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
There have been numerous issues about this exact problem already: https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues?q=MissingPluginException
For example, most recently, #102 and #126
Please look there if they solve the problem. In the mean time, I will close this issue
