### ISSUE TITLE
Add the ability to support launching webview URLs with the same scheme as redirect URL

### ISSUE THREAD

**Issue by graylandl-vpitech** [ThexXTURBOXx/flutter_web_auth_2#146]
## Is your feature request related to a problem? Please describe.
On Lindows, when using a OAuth launch URL passed to authenticate() with the same scheme as the provided callback scheme, the webview window is immediately closed with the result being the same as the launch URL.

## Describe the solution you'd like
(going to submit PR)

Extend implementation to check options['httpsHost'] and options['httpsPath'] in the webview's OnUrlRequestCallback if provided in Lindows implementation.

## Describe alternatives you've considered
- Check the cb url and the launch url, verify that the callback url is not the same as authUrl 
``` dart
authorize(string authUrl, ...){... addOnUrlRequestCallback(url){if(url == authUrl){return;}}}
```
- This has the potential to break backwards compatibility in the case that a developer initializes the window with a cb url (may be misuse of the package, so could be okay to break compatibility with this case.)

**Comment by ThexXTURBOXx** [comment]
Thanks for the issue - this is now available as part of 4.1.0!
