### ISSUE TITLE
[Bug]: Error in iOS after switching to this package

### ISSUE THREAD

**Issue by 7h30n3** [ThexXTURBOXx/flutter_web_auth_2#147]
### Description

We implemented Android App Links using `flutter_web_auth`.  In the hope of Apple Universal Links to work we switched to  `flutter_web_auth_2`.
After making sure that everything in Android works as with the old package, we tested iOS, but when calling `FlutterWebAuth2.authenticate` by clicking on the login button, we get this error:

```
flutter: PlatformException(CANCELED, User canceled login, null, null)
```

### Minimal Reproduction

We used the [migration guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2?tab=readme-ov-file#upgrading-from-flutter_web_auth):

In `AndroidManifest.xml `we added `_2`:
```xml
        <activity android:name="com.linusu.flutter_web_auth_2.CallbackActivity" android:launchMode="singleTop" android:exported="true">
            <intent-filter android:label="flutter_web_auth_2" android:autoVerify="true">
```

In `authenticate.dart` we replaced the imported package (obviously :)) and this:

```dart
    final result = await FlutterWebAuth.authenticate(
      url: authUri.toString(),
      callbackUrlScheme: app_config.appCallbackUrlScheme,
      preferEphemeral: true,
    );
```

with this:

```dart
    final result = await FlutterWebAuth2.authenticate(
      url: authUri.toString(),
      callbackUrlScheme: app_config.appCallbackUrlScheme,
      options: const FlutterWebAuth2Options(
        preferEphemeral: true,
        httpsHost: 'appname.com',
        httpsPath: '/oauth2'
      ),
    );
```

To Info.plist we also added:

```xml
<key>FlutterDeepLinkingEnabled</key>
<true/>
```

To `Runner.entitlements `we added:

```xml
 <array>
       <string>applinks:appname.com?mode=developer</string>
       <string>webcredentials:appname.com?mode=developer</string>
</array>
```

### Exception or Error

`flutter: PlatformException(CANCELED, User canceled login, null, null)`

### Expected Behaviour

With the old package (`flutter_web_auth`) after clicking on the login button the browser appeared asking for login credentials. After authorizing we landed on an 404-page (and not back in the app). That was the reason for switching to `flutter_web_auth_2` in the first place.

### Device

iPhone 13 mini (iOS 18.2); iOS Emulator (iOS 17.5)

### OS

MacOS

### Browser

Safari

### Flutter version

3.24.4

### flutter_web_auth_2 version

4.1.0

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Thanks for the report. I see that you are trying to use `httpsHost` and `httpsPath`, but also specify the callback URL scheme as `app_config.appCallbackUrlScheme`. Are you sure this is correct? Shouldn't it be just `"https"`?

**Comment by 7h30n3** [comment]
Thanks for the quick response. `app_config.appCallbackUrlScheme` is read from another file and is the result of this function:

```dart
const appCallbackUrlScheme = kIsWeb && !bool.fromEnvironment('IS_RELEASE', defaultValue: false)
    ? 'http'
    : 'https';
```
So building the app for iOS actually resolves this to `https`.

**Comment by ThexXTURBOXx** [comment]
Okay, in that case, this might be a duplicate of #123 - can you verify that `preferEphemeral: false` makes authentication work?

**Comment by 7h30n3** [comment]
Unfortunately, that doesn't change anything.
The exception appears as soon as this function is called: https://github.com/ThexXTURBOXx/flutter_web_auth_2/blob/master/flutter_web_auth_2_platform_interface/lib/method_channel/method_channel.dart#L9

Below you can see the call stack:
<img width="425" alt="Screenshot 2024-12-09 at 09 19 44" src="https://github.com/user-attachments/assets/112022a9-7410-46d8-a885-1ea2e0b43f7b">

**Comment by fefsouza10** [comment]
Someone managed to solve this? I'm facing the same issue.

**Comment by 7h30n3** [comment]
I fixed the issue. Turns out this package works fine and the mistake was made by me.

To get to the button of this I built the app in Xcode and set a breakpoint at https://github.com/ThexXTURBOXx/flutter_web_auth_2/blob/8057fa8cd3d5f15539032c79ba209d99f9e4bb3b/flutter_web_auth_2/ios/Classes/SwiftFlutterWebAuth2Plugin.swift#L37

The error message said:
`Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=1 "Application with identifier TEAM-ID.BUNDLE-ID is not associated with domain DOMAIN. Using HTTPS callbacks requires Associated Domains`

Which made me curious, because I configured everything according to the documentation and also the check using `swcutil` ([Apple documentation](https://developer.apple.com/documentation/technotes/tn3155-debugging-universal-links#Host-and-verify-your-AASA)) was successful. However doing a sysdiagnose  also showed me `Site/Fmwk Approval:   denied`.

The breakthrough came with testing the Universal Links on an physical iOS device under Developer settings > Associated Domains > Diagnostics after installing my app. Entering my domain it told me `The URL is a Universal Links for the app with the identifier TEAM-ID.TEAM-ID.BUNDLE-ID`. (Retrospectively this could also be seen in the sysdiagonse)

So I opened project.pbxproj file and removed the TEAM.ID from the key `PRODUCT_BUNDLE_IDENTIFIER`. So for example from this `1234ABCD.com.example.myapp` to `com.example.myapp`.

What can be written in a few sentences took me quite a while to figure out. I hope it helps someone else.

**Comment by fefsouza10** [comment]
Hi, just to add a possible solution for everyone lost in this issue like I was in the past 24 hours.

What was missing for me, is that in Associated Domains in XCode, It was missing the "webcredentials" parameter. I set just the "applinks". After adding the "webcredentials", everything works.

Using Universal Links, with 'https' as callbackScheme.

**Comment by ThexXTURBOXx** [comment]
Thanks for all the explanations - I do not own any Apple device, so I cannot test on macOS and/or iOS. But, I will try to add all this information to the troubleshooting guide!
