### ISSUE TITLE
[Bug]: <"name" field doesn't match expected name "flutter_web_auth". while flutter pub get>

### ISSUE THREAD

**Issue by iqbal-k** [ThexXTURBOXx/flutter_web_auth_2#151]
### Description

dependency_overrides:
  flutter_web_auth:
    git: 'https://github.com/ThexXTURBOXx/flutter_web_auth.git'
    
    i was using GitHub version of flutter_web_auth while installing i am getting error ""name" field doesn't match expected name "flutter_web_auth"

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
    <Paste your code here>
    ```
2. [...]

### Exception or Error

"name" field doesn't match expected name "flutter_web_auth".

### Expected Behaviour

"name" field doesn't match expected name "flutter_web_auth".

### Device

android

### OS

null

### Browser

null

### Flutter version

3.27.0

### flutter_web_auth_2 version

git: 'https://github.com/ThexXTURBOXx/flutter_web_auth.git'

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Why are you using a dependency override still?
