### ISSUE TITLE
Change iOS dialog text

### ISSUE THREAD

**Issue by gauravmehta13** [ThexXTURBOXx/flutter_web_auth_2#18]
When using the plugin on iOS for first time it asks 
"test.com" would like to sign in.
Is these any way to change this text since I am using the package for payment and not for Sign In

**Comment by ThexXTURBOXx** [comment]
This seems to be a limitation with the `ASWebAuthenticationSession`:
https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession
At least, I cannot find hints on how to change this in the documentation.
