### ISSUE TITLE
can support Flutter SDK version is 2.8.0 ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [ThexXTURBOXx/flutter_web_auth_2#3]
can support Flutter SDK version is 2.8.0 ?

**Comment by ThexXTURBOXx** [comment]
Hi, this plugin won't give you much of a benefit when using it with 2.8.0. The intention was specifically to provide the best of experience to users on the newest version of Flutter.
If you want to stick with an old version of Flutter, just continue using the original `flutter_web_auth` project. You will only be missing out some Bugfixes, refactors, and windows support.
