### ISSUE TITLE
[Web] Detect login tab was closed or cancelled 

### ISSUE THREAD

**Issue by adar2378** [ThexXTURBOXx/flutter_web_auth_2#37]
## Describe the bug
On web we’re using this package for discord login. ‘authenticate’ method opens a new tab with the proper url. But when I close the new tab, in the flutter app ‘authenticate’ method stays running. Could you please help us how can we resolve it?

**Comment by ThexXTURBOXx** [comment]
Please fill out the appropriate issue template
