### ISSUE TITLE
Authenticate in multiple activities

### ISSUE THREAD

**Issue by KoheiYamashita** [ThexXTURBOXx/flutter_web_auth_2#38]
## Describe the bug
Our app has two activities implemented: ActivityA and ActivityB.
When executing the authenticate function in ActivityB, it redirects to ActivityA.

## To Reproduce
1. Launch the ActivityB.
2. Execute the authenticate function.
3. Observe the redirect to ActivityA.

## Expected behavior
Redirect to the Activity that performed the authenticate.

## Screenshots
Not applicable.

## Device
 - Device: Pixcel7Pro
 - OS: Android13
 - Browser: Chrome
 - `flutter_web_auth_2` version: 2.1.2

## Additional context
ActivityA has the following intent-filter:
```
<intent-filter>
  <action android:name="android.intent.action.MAIN"/>
  <category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
```

This filter is used to launch the main screen of the app.

ActivityB is set up to receive text data with the following intent-filter:

```
<intent-filter>
  <action android:name="android.intent.action.SEND"/>
  <category android:name="android.intent.category.DEFAULT"/>
  <data android:mimeType="text/plain"/>
</intent-filter>
```

CallbackActivity is defined as follows.
```
<activity
    android:name="com.linusu.flutter_web_auth_2.CallbackActivity"
    android:exported="true">
        <intent-filter android:label="flutter_web_auth_2">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="com.example.oauth" android:host="callback" />
          </intent-filter>
</activity>
```

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [x] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
Thanks for reporting the bug, I will take a look at it soon

**Comment by KoheiYamashita** [comment]
Hello. I'm currently checking how to use it, and it seems that using ActivityAware allows you to obtain the associated Activity.
I hope this helps with your analysis!

**Comment by KoheiYamashita** [comment]
Thank you very much.
After trying various things like changing the launchMode, it seems that it was being redirected to the main task.
I guess this is probably the standard behavior of the plugin. I will let you know if I find a workaround, but for now, I'm thinking of closing this issue. Is that okay?

**Comment by ThexXTURBOXx** [comment]
No problem! If you find some workaround, please let me know. Then I can extend the troubleshooting guide.
Thank you very much!
