### ISSUE TITLE
Closing the authentication tab keeps authenticate method running

### ISSUE THREAD

**Issue by s9th** [ThexXTURBOXx/flutter_web_auth_2#39]
## Describe the bug
If the authentication tab in the browser is closed before receiving the authentication result, the FlutterWebAuth2.authenticate keeps running.

## To Reproduce
1. Start authentication with a provider that has a dialog asking the user to approve scopes (e.g. Github with scopes repo, project)
2. Close the github browser tab
3. FlutterWebAuth2.authenticate runs indefinitely

## Expected behavior
FlutterWebAuth2.authenticate returns null or throws an Exception

## Screenshots
Line 26 is never reached if browser tab is closed
![image](https://user-images.githubusercontent.com/15362801/230177878-605ab80b-cd5e-4078-b469-60b91e4b1a89.png)

## Device (please complete the following information!)
 - Device: Desktop Computer
 - OS:  Windows 11 22H2
 - Browser:  Chrome,
 - `flutter_web_auth_2` version: 2.1.2

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [x] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
I also thought about some mechanism that could detect cases like this, but don't know what the best solution would be.
However, I will try to fix this issue soon

**Comment by DragonSlayer88** [comment]
Any update on this? Im having the same issue

**Comment by ThexXTURBOXx** [comment]
Sorry, no update yet as I had no time to work on it due to my master thesis

**Comment by Sten435** [comment]
Any update on this?

It would be nice if we could specify a timeout duration or smtg...

**Comment by ThexXTURBOXx** [comment]
I am finally back from my vacation and this issue should be fixed in the new `2.2.1` release

**Comment by Sten435** [comment]
> I am finally back from my vacation and this issue should be fixed in the new `2.2.1` release

Thanks mate 👌

**Comment by ThexXTURBOXx** [comment]
The timeout is now configurable in `3.0.0-alpha.1`
