### ISSUE TITLE
[flutter_web_auth]  sign in with goolge faild .

### ISSUE THREAD

**Issue by Joseph-Nathan** [ThexXTURBOXx/flutter_web_auth_2#4]
when move to browser i get this Error

 Error 400: redirect_uri_mismatch 
you can't sign in to this app because it doesn't comply with google's oauth 2.0 policy ,

but i check redirect_uri in my [ firebase auth , google cloud console , my app ] it's a same ,
i can't find the problem ,
should i add Authorized JavaScript origins to google cloud console , 
 i used the package from android app .

**Comment by ThexXTURBOXx** [comment]
Please follow the issue template. Otherwise I am not able to reproduce your problem.

**Comment by Joseph-Nathan** [comment]
sorry , i solve this by
replace :
  'redirect_uri' : '$callbackUrlScheme:/' ,
 by :
  'redirect_uri' :    callbackUrlScheme  ,

, but i get this error after i choose google account :
`Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.`

**Comment by Joseph-Nathan** [comment]
i think this Error from my backend "Firebase" not from this package ,
thanks bro for wonderful package ,
and if you get any solution i'm ready to hear .

**Comment by Joseph-Nathan** [comment]
can we used web-view instead of external tab ??

**Comment by ThexXTURBOXx** [comment]
The new problem seems to be related to something other then this package.

Related to the external tab problem: That would be a nice feature request. Could you maybe create a new issue for that such that I can keep track of this? :)
