### ISSUE TITLE
Failed to build (APK/Appbundle) on Android

### ISSUE THREAD

**Issue by teoprayoga** [ThexXTURBOXx/flutter_web_auth_2#45]
Iam using package appwrite pub dev which depends on this package. when i build IOS working fine, but when i build APK/Appbundle Android it showing error that says:

* What went wrong:
A problem occurred evaluating project ':flutter_web_auth_2'.
 > No signature of method: build_br839y3cjw240hfyqvnkgs25f.android() is applicable for argument types: (build_br839y3cjw240hfyqvnkgs25f$_run_closure2) values: [build_br839y3cjw240hfyqvnkgs25f$_run_closure2@54024517]

my flutter version: 3.3.8

**Comment by ThexXTURBOXx** [comment]
This is because of the new AGP requirements of this package.
You need to update your android gradle plugin to at least 7.x.
