### ISSUE TITLE
iOS Opening File Insted of URL [Authenticate Call]

### ISSUE THREAD

**Issue by rdunlocked18** [ThexXTURBOXx/flutter_web_auth_2#52]
After calling this authenticate method on my auth URL on IOS it is opening like this. Whereas on all other platforms it is opening correctly.

## To Reproduce
1. Go to 'await FlutterWebAuth2.authenticate()'
2. I am using Salesforce login redirect. 
3. Works on all other platforms but Showing below thing on iOS.

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-25 at 09 39 59](https://github.com/ThexXTURBOXx/flutter_web_auth_2/assets/29021926/f0f97657-aa1e-4567-9a2e-495ee19f5823)

**Comment by ThexXTURBOXx** [comment]
This looks like "Apple being Apple" again. I am unsure if this is a bug within this package or iOS or the backend since there is no way for me to test that (I don't own a apple device)

**Comment by ThexXTURBOXx** [comment]
Have you found a solution for this problem? If yes, would you be able to share how to resolve it for any other users that might have the issue? :)
Thank you very much in advance!
