### ISSUE TITLE
Unable to build on MacOS after raising minimum target version to 10.15 (11.0)

### ISSUE THREAD

**Issue by KartikAiyer** [ThexXTURBOXx/flutter_web_auth_2#54]
## Describe the bug
Attempting to build for MacOS fails with cocopods install step failing. I've tried raising the minimum target version in the MacOs Podfile as well as in XCode Project but I still see the error. 
```
dlopen(/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): Library not loaded
```
Also I've tried all the main suggestions of reinstalling `gem` and `cocoapods` and updating Ruby and in all cases I still see the same problem. 

I thought this was a flutter issue to begin with and [posted here](https://github.com/flutter/flutter/issues/131238) but I was informed that it was likely due to my target version in the MacOS app. 

I have not tried to build this for iOS but suspect that I will run into the same issue and probably has the same fix of updating the target version appropriately. 

I'm not sure if I'm currently updating the minimum target version correctly or if there are some other places that I'm missing out on in order to get this to work.

## To Reproduce
1. Create a new flutter project `flutter create bug --platforms macos`
2. Add the Flutter Web Auth 2 as a dep: `flutter pub add flutter_web_auth_2`
3. Raise minimum target version in Podfile and in XCode Project
    * I modify the first line of the Podfile in the macos folder setting the version to 10.15 (i've tried 11.0 too).
      * `platform :osx, '11.0'`
    * I open the XCode Project -> Runner -> Target -> Runner -> Minimum Target Version -> 10.15 (or 11.0)
5. In the macos folder invoke pod install `cd macos; pod install`

```
dlopen(/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): Library not loaded
```
## Expected behavior
I should be able to build on Mac OS.

## Screenshots
Updated Mac OS Minimum Target version in the Xcode prooject
![Screenshot 2023-07-30 at 1 32 31 PM](https://github.com/ThexXTURBOXx/flutter_web_auth_2/assets/2114735/5ebe39da-6d49-4b0e-b591-d8cf403711a5)

## Device (please complete the following information!)
 - Device: Macbook Air M1
 - OS: 13.4.1 
 -  Browser: Chrome
 - `flutter_web_auth_2` version: 2.1.5
 
## Checklist
 - [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [X] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
This seems to have been fixed by the comment in the linked issue
