### ISSUE TITLE
Safari shows Pop-up window blocked

### ISSUE THREAD

**Issue by bhavinmdesai** [ThexXTURBOXx/flutter_web_auth_2#55]
When using `flutter_web_auth_2: ^2.1.5` and when I call authenticate without passing any `contextArgs`, the safari blocks open up in a new tab and say`Pop-up window blocked`.

**Comment by ThexXTURBOXx** [comment]
Sadly, I have no Apple device to debug that on. So someone else needs to do that, sadly

**Comment by krille-chan** [comment]
Same here. Also reported by our customers on Edge and even Chrome sometimes

**Comment by Hamidrzash** [comment]
I'm also having this issue on nearly all browsers

**Comment by ThexXTURBOXx** [comment]
Sadly, still not reproducible on my end with the [example](https://github.com/ThexXTURBOXx/flutter_web_auth_2/tree/master/flutter_web_auth_2/example)

**Comment by alfaruqrizqi18** [comment]
Facing same issue here, tried to authenticate Tiktok. Need to open it in new window popup instead new tab

**Comment by ThexXTURBOXx** [comment]
Please try the new prereleases for 3.x. They use `url_launcher` to open the URL. If it is still an issue then, please report this bug to them.

**Comment by ThexXTURBOXx** [comment]
As this is no longer in my hands, I will close this issue. For further problems, please report to `url_launcher`.
