### ISSUE TITLE
Change win32 dependency version

### ISSUE THREAD

**Issue by tulioccalazans** [ThexXTURBOXx/flutter_web_auth_2#6]
## Description

Hi, could you change win32 dependency version to ^2.0.0?

You lib is causing error on pub get command:

`Because flutter_web_auth_2 >=1.1.0 depends on flutter_web_auth_2_windows ^1.1.0 which depends on win32 ^3.0.0, flutter_web_auth_2 >=1.1.0 requires win32 ^3.0.0.
Because path_provider_windows >=2.1.1 depends on win32 ^2.1.0 and path_provider_windows >=2.0.0 <2.1.1 depends on win32 ^2.0.0, path_provider_windows >=2.0.0 requires win32 ^2.0.0.
Thus, flutter_web_auth_2 >=1.1.0 is incompatible with path_provider_windows >=2.0.0.
And because shared_preferences_windows >=2.0.0 depends on path_provider_windows ^2.0.0, flutter_web_auth_2 >=1.1.0 is incompatible with shared_preferences_windows >=2.0.0.
And because shared_preferences 2.0.15 depends on shared_preferences_windows ^2.0.1 and no versions of shared_preferences match >2.0.15 <3.0.0, flutter_web_auth_2 >=1.1.0 is incompatible with shared_preferences ^2.0.15.
So, because qapp2 depends on both shared_preferences ^2.0.15 and flutter_web_auth_2 ^1.1.0, version solving failed.
pub get failed (1; So, because qapp2 depends on both shared_preferences ^2.0.15 and flutter_web_auth_2 ^1.1.0, version solving failed.)`

## To Reproduce
```
Just add shared_preferences: ^2.0.15 dependency or package_info_plus: ^1.4.3+1
```

**Comment by ThexXTURBOXx** [comment]
I have the same error in a project of mine. Just use `^1.0.1` as `flutter_web_auth_2` version until the other packages are updated :)

**Comment by ThexXTURBOXx** [comment]
Even though I really do not like the idea of such version ranges being used inside `pubspec`, I decided to loosen the constraint
