### ISSUE TITLE
Make the 'you may now close this page' html customizable

### ISSUE THREAD

**Issue by Sten435** [ThexXTURBOXx/flutter_web_auth_2#60]
It would be nice if we could give a html as an option instheid of the hard coded you may know close this page.

A sepperate html and css file and or a js file would be nice as an option.

Thanks

**Comment by ThexXTURBOXx** [comment]
If you are talking about the `auth.html` page for Web, it is already fully customizable. The only thing it needs is the Javascript inside it.
However, it is a good idea to make the Windows and Linux landing pages customizable. I will release this as part of `3.0.0-alpha.2` in a few hours.

**Comment by ThexXTURBOXx** [comment]
New version has been published!
