### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by meroo36** [ThexXTURBOXx/flutter_web_auth_2#62]
## Describe the bug
App crashes after second time I initialize oauth2 flow in IOS.

## To Reproduce
1. Click on a dynamic link to initialize the app with oauth flow 
2. Authentication completes succesfully
3. Everthing works unless you click the dynamic link once more
4. You see the error: flutter_web_auth_2/SwiftFlutterWebAuth2Plugin.swift:29: Fatal error: Unexpectedly found nil while unwrapping an Optional value

## Device (please complete the following information!)
 - Device: Iphone 13
 - OS: iOS 16.1.1
 - `flutter_web_auth_2` version: 2.2.1

**Comment by meroo36** [comment]
My guess is the sessionToKeepAlive variable is beeing nil for the second time. 

```swift
var sessionToKeepAlive: Any? // if we do not keep the session alive, it will get closed immediately while showing the dialog
            completionHandler = { (url: URL?, err: Error?) in
                self.completionHandler = nil
                
                if #available(iOS 12, *) {
                    (sessionToKeepAlive as! ASWebAuthenticationSession).cancel() // Error Happens this line 29 in SwiftFlutterWebAuth2Plugin
                } else if #available(iOS 11, *) {
                    (sessionToKeepAlive as! SFAuthenticationSession).cancel()
                }
                
                sessionToKeepAlive = nil

```

**Comment by meroo36** [comment]
I could fix the issue by wrapping the oauth2 call with a timer. I guess you need to wait a little untill the app is on the foreground succesfully. 

```dart
        Timer(Duration(milliseconds: lazyLoginDelayTime), () async {
          List<String> scopes = ["*****", "******"];
          await account.createOAuth2Session(
              provider: "*******", scopes: scopes);
          await ref.read(authProvider.notifier).login();
        });
```


Closing for now.

**Comment by andreivarlamov** [comment]
Same issue, is it fixed in the 3.0.0?

**Comment by ThexXTURBOXx** [comment]
I think I have changed nothing in the Apple-specific implementations.
Also, I don't have any Apple hardware, so I cannot properly debug these issues. PRs are welcome, though.

**Comment by ozzy1873** [comment]
Here is a stack trace, perhaps it will help:

#0	(null) in Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value ()

#1	0x000000010416d06c in closure #1 in SwiftFlutterWebAuth2Plugin.handle(_:result:) at /Users/xxx/.pub-cache/hosted/[pub.dev/flutter_web_auth_2-2.2.1/ios/Classes/SwiftFlutterWebAuth2Plugin.swift:29](http://pub.dev/flutter_web_auth_2-2.2.1/ios/Classes/SwiftFlutterWebAuth2Plugin.swift:29)

#2	0x000000010416cc08 in closure #1 in SwiftFlutterWebAuth2Plugin.handle(_:result:) at /Users/xxx/.pub-cache/hosted/[pub.dev/flutter_web_auth_2-2.2.1/ios/Classes/SwiftFlutterWebAuth2Plugin.swift:29](http://pub.dev/flutter_web_auth_2-2.2.1/ios/Classes/SwiftFlutterWebAuth2Plugin.swift:29)

#3	(null) in thunk for @escaping @callee_guaranteed (@in_guaranteed URL?, @guaranteed Error?) -> () ()

#4	(null) in -[ASWebAuthenticationSession _startDryRun:] ()

#5	0x000000010416ebb8 in specialized SwiftFlutterWebAuth2Plugin.handle(_:result:) at /Users/xxx/.pub-cache/hosted/[pub.dev/flutter_web_auth_2-2.2.1/ios/Classes/SwiftFlutterWebAuth2Plugin.swift:100](http://pub.dev/flutter_web_auth_2-2.2.1/ios/Classes/SwiftFlutterWebAuth2Plugin.swift:100)

#6	(null) in specialized SwiftFlutterWebAuth2Plugin.handle(_:result:) ()

#7	(null) in @objc SwiftFlutterWebAuth2Plugin.handle(_:result:) ()

**Comment by ThexXTURBOXx** [comment]
Will close for now until further feedback on `3.x`
