### ISSUE TITLE
HTTPS Scheme

### ISSUE THREAD

**Issue by vitortoigo** [ThexXTURBOXx/flutter_web_auth_2#63]
I'm using flutter_webview and want integrate OAuth.
Any methods to use https scheme?

Just dont return back to my flutter app after authentication.

Like this:

`
<data android:scheme="https" android:host="mydomain.com" android:pathPrefix="/callback" />
`

`await FlutterWebAuth2.authenticate(
    url: request.url,
    callbackUrlScheme: 'https',
);`

**Comment by ThexXTURBOXx** [comment]
Please follow the issue template and read the troubleshooting guide.
