### ISSUE TITLE
Need help for login with tiktok

### ISSUE THREAD

**Issue by alfaruqrizqi18** [ThexXTURBOXx/flutter_web_auth_2#64]
## Description
Hi, after redirected to tiktok authorize and redirect uri, still not getting the result

## To Reproduce
```dart
Future<String?> connect() async {
    // Construct the url
    const String callbackUrlScheme = 'https://example.com/oauth2redirect?social=Tiktok';
    final url = Uri.https('www.tiktok.com', '/auth/authorize/', {
      'client_key': '***********',
      'response_type': 'code',
      'scope': 'user.info.basic,video.list',
      'redirect_uri': callbackUrlScheme,
      'state': 'Tiktok',
    });

    try {
      final result = await FlutterWebAuth2.authenticate(
        url: url.toString(),
        callbackUrlScheme: 'https',
      );
      // String accessToken = Uri.parse(result).queryParameters['code'] ?? "";
      return Uri.parse(result).toString();
    } catch (e) {
      print("Error -> ${e.toString()}");
    }
  }
```

## Expected behavior
Need to get the result after authorized from tiktok and redirect_uri

## Device (please complete the following information!)
 - Device: [Acer 475g]
 - OS: [Windows 10 20H2]
 - Browser: [Chrome]
 - `flutter_web_auth_2` version: [2.2.1]

## Checklist
 - [ ] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [ ] I have provided all the information I can (incl. auth URL etc.)

**Comment by alfaruqrizqi18** [comment]
Is something missing with my code? @ThexXTURBOXx

**Comment by ThexXTURBOXx** [comment]
First read through the troubleshooting guide please as indicated by the issue template.
Also, I need further information: Are you compiling your application for Windows or Web or something different?

**Comment by alfaruqrizqi18** [comment]
Still confusing about callbackUrlScheme, because from tiktok redirect_uri is to my webpage
Ex : my redirect_uri in tiktok -> https://example.com/oauth2redirect?social=Tiktok, so what is the callbackUrlScheme?

I'm using this for web

**Comment by alfaruqrizqi18** [comment]
> Still confusing about callbackUrlScheme, because from tiktok redirect_uri is to my webpage Ex : my redirect_uri in tiktok -> https://example.com/oauth2redirect?social=Tiktok, so what is the callbackUrlScheme?
> 
> I'm using this for web

Can help this? @ThexXTURBOXx 
I don't know what is callbackUrlScheme for web

**Comment by ThexXTURBOXx** [comment]
You need to read through the readme for the setup instructions and the troubleshooting guide for further help.

**Comment by alfaruqrizqi18** [comment]
> You need to read through the readme for the setup instructions and the troubleshooting guide for further help.

I have read readme for the setup instructions and the troubleshooting guide. But still can't get the result

**Comment by alfaruqrizqi18** [comment]
also have created `auth.html`

**Comment by ThexXTURBOXx** [comment]
Then, why are you still not redirecting to the `auth.html` page as described in the Readme?

**Comment by alfaruqrizqi18** [comment]
When this code called
```dart
final result = await FlutterWebAuth2.authenticate(
  url: url.toString(),
  callbackUrlScheme: 'https',
);
```

It will open new tab with this url and parameter
```dart
Uri.https('www.tiktok.com', '/auth/authorize/', {
      'client_key': '***********',
      'response_type': 'code',
      'scope': 'user.info.basic,video.list',
      'redirect_uri': 'https://example.com/oauth2redirect?social=Tiktok',
      'state': 'Tiktok',
    })
```
After tiktok page is open, I just need to click **Authorize** Button and then if authorize is successfull, from tiktok will redirect automatically to this `'https://example.com/oauth2redirect?social=Tiktok'`

After redirected to that page, the tab isn't closed. That's why I ask you to help.
Is this code still wrong or something? because I don't know the callbackUrlScheme, so I added the **https**
```dart
final result = await FlutterWebAuth2.authenticate(
  url: url.toString(),
  callbackUrlScheme: 'https',
);
```
@ThexXTURBOXx

**Comment by ThexXTURBOXx** [comment]
The `callbackUrlScheme` is ignored on the Web version.
You need tiktok to redirect to the `auth.html` page as described in the Readme.
