### ISSUE TITLE
Unable to redirect windows app when browser tab closed time

### ISSUE THREAD

**Issue by Anish8940** [ThexXTURBOXx/flutter_web_auth_2#67]
## Describe the bug
Unable to redirect windows app when browser tab closed time

## To Reproduce
1) Open Windows app
2) Pass the url to flutter authenticate
3) New broser tab was opened and app was loaded in background
4) Close the browser tab 
5) App always loading state.

## Expected behavior
Tab was closed time we need to hide loading page

**Comment by ThexXTURBOXx** [comment]
You cannot simply check when a tab is closed in some browser.
Because of this, there is a timeout (which is fixed in versions `<= 2.x` and adjustable in versions `>= 3.x`).
If you want to change the timeout value, try out the alpha releases for `3.x`.

**Comment by Anish8940** [comment]
Ok. Thank you for you fastest reply @ThexXTURBOXx
