### ISSUE TITLE
Windows: Missing Plugin Implementation

### ISSUE THREAD

**Issue by 2002Bishwajeet** [ThexXTURBOXx/flutter_web_auth_2#7]
## Describe the bug
When I authenticate to my custom backend in the windows app, I get this error!
`Error: MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)`

I believed in [`pub.dev/flutter_web_auth_2`](https://pub.dev/packages/flutter_web_auth_2) , it shows the support for windows as well

## To Reproduce
1. You can run the example given in the package itself

## Expected behavior
It should work

## Device (please complete the following information!)
 - Device: Desktop Computer
 - OS: [e.g. iOS 8.1, Windows 11 22H2]
 - `flutter_web_auth_2` version: 1.0.1 (can't use 1.1.0 due to dependency constraints with `device_info_plugin`)

## Additional context
Maybe I am missing some documentation here or somethings not working internally.

**Comment by ThexXTURBOXx** [comment]
That's weird. I thought I had tested this... I will test again and fix as soon as possible!

**Comment by 2002Bishwajeet** [comment]
Thanks for the quick response😄

**Comment by ThexXTURBOXx** [comment]
I have fixed this issue and am trying to publish the new version right now. However, there are some difficulties with publishing for some reason. I will see what I can do!

**Comment by ThexXTURBOXx** [comment]
New version successfully published! Something in my dart caches was broken...

**Comment by 2002Bishwajeet** [comment]
Quick question:  If I update to the latest version, wouldn't I face dependency conflicts with `win32`?  Cause as mentioned before `device_info_plus` still depends on 2.7.0 on win32 and this package supports 3.0.0

**Comment by ThexXTURBOXx** [comment]
Yes, someone has to push the `plus_plugins` community to update to `win32`. Maybe I can even do it, let's see

**Comment by 2002Bishwajeet** [comment]
I found a hack for now. use dependencies overrides https://dart.dev/tools/pub/dependencies#dependency-overrides
```dart
dependency_overrides:
  win32: '2.7.0'
```

**Comment by 2002Bishwajeet** [comment]
Hey @ThexXTURBOXx  , I do have one  question. Why does callbackurl scheme must start with `https://localhost:port` for windows implementation??

**Comment by ThexXTURBOXx** [comment]
That is just a limitation that is needed for now. If you are able to achieve a working Windows implementation any other way, please let me know (or even better) open a PR :)

**Comment by ThexXTURBOXx** [comment]
@2002Bishwajeet I have loosened the constraint on `win32`. You can now get rid of the `dependency_override`. However, package upgrades in `path_provider` and two `plus_plugins` are already on their way.
