### ISSUE TITLE
White screen when authenticating

### ISSUE THREAD

**Issue by Sinan-Karakaya** [ThexXTURBOXx/flutter_web_auth_2#70]
## Describe the bug
When opening a url for me to authenticate to, the external chrome tab stays white, thus preventing me from authenticating myself.

## To Reproduce
Trigger this function

```dart
Future<void> SpotifyLogin() async {
    String url = "https://accounts.spotify.com/authorize?client_id=$spotifyClientID&redirect_uri=area&scope=user-read-currently-playing&response_type=token&state=123";

    final result = await FlutterWebAuth2.authenticate(url: url, callbackUrlScheme: "area");
    final token = Uri.parse(result).queryParameters["token"];
    if (kDebugMode) {
      print(token);
    }
  }
```

## Expected behavior
It should open the webview of the Spotify login page, and send me my token back.

## Screenshots
![image](https://github.com/ThexXTURBOXx/flutter_web_auth_2/assets/91690021/53fe8531-37ba-4a44-ad06-c4cc066a45e6)

## Device (please complete the following information!)
 - Device: Tiramisu emulator
 - OS: Windows 11 22H2
 - Browser: not using a browser
 - `flutter_web_auth_2` version: 2.2.1

## Additional context
I did added the Internet permission (correctly if SO is to be believed) as this was my first guess

## Checklist
 - [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [X] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
Loading webpages is handled by Chrome Custom Tabs. If there is a problem with that, try asking on StackOverflow instead.
