### ISSUE TITLE
White Screen when trying to authenticate with Azure AD

### ISSUE THREAD

**Issue by OzyOzk** [ThexXTURBOXx/flutter_web_auth_2#71]
## Describe the bug
My Azure login page isn't loading when I try to authenticate with Azure AD. 

## To Reproduce
```
class AzureAuthentication{
  String authority = "login.microsoftonline.com";
  String redirect = "https://login.live.com/oauth20_desktop.srf";
  void authenticate() async {
    final redirect_uri = Uri.parse(redirect);
    final red = redirect_uri.toString();
    final url = Uri.https(authority, "/$tennant_id/oauth2/v2.0/authorize/", {
      'response_type': 'code',
      'client_id': client_id,
      'redirect_uri': redirect,
      'scope': 'openid'
    });
    print("1");
    final res = await FlutterWebAuth2.authenticate(url: url.toString(), callbackUrlScheme: "https");
    print("2");
    final code = Uri.parse(res).queryParameters['code'];
    print(code);
  }
  
}
```

## Expected behavior
The page should load the MS Azure Login page

## Device (please complete the following information!)
 - Device: pixel 5
 - OS: Android
 - Browser: Chrome
 - `flutter_web_auth_2` version: 2.2.1

## Additional context
Not sure what the redirect URL scheme is for AD. Haven't found anything online around this library and Azure

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [x] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
Loading web pages is handled by Chrome Custom Tabs. If there is a problem with loading a page, it is not an issue with this package.
Try asking on StackOverflow.
