### ISSUE TITLE
Browser new window was not opened in windows platform

### ISSUE THREAD

**Issue by Anish-T-GitHub** [ThexXTURBOXx/flutter_web_auth_2#73]
## Describe the bug
I used this library in windows. I already login the  **URL(' https://ip:port/login')** on chrome browser after i try to authenticate this URL **('https://ip:port/desktop_login') via windows app** but new login window was not displayed. 

**IP and Port was same**

**Chrome login URL :** https://ip:port/login
**Windows app login URL :** https://ip:port/desktop_login

## To Reproduce
**Steps to reproduce the behavior:**
1. Open Chrome
2. login this **https://ip:port/login**
3. once login process was completed on web after try to authenticate this URL **https://ip:port/desktop_login**
4. New window was not opened on windows platform

## Expected behavior
I need to open new login page

## Device (please complete the following information!)
 - Device: Dell Latitude
 - OS: Windows 10
 - Browser: Chrome
 - `flutter_web_auth_2` version: [2.2.1]

**Comment by ThexXTURBOXx** [comment]
Why do you need to log in two times?
You need two different calls to `authenticate` since the internal server gets closed as soon as some result is received.

**Comment by Anish-T-GitHub** [comment]
We have different platform products we try to login the same URL at different platforms 
but this flow working fine on MAC i set preferEphemeral = true on MAC

**Comment by Anish-T-GitHub** [comment]
I already logined the URL on **chrome browser** **after i pass the URL to flutter web authenticate via flutter windows platform**  that time **window tab was not opened** in browser but this flow working fine on MAC i set preferEphemeral = true on MAC
