### ISSUE TITLE
error with the gradle version

### ISSUE THREAD

**Issue by lovecraftHP** [ThexXTURBOXx/flutter_web_auth_2#75]
## Description
I just working on a new project that uses this plugin but I have been having problems building the project, always shows a message that says

_** Unsupported class file major version 61**_ 

indicate that I need to use the correct gradle version in the gradle-wrapper.properties. The main problem is that already using

* Java 18
* Gradle suggested version 7.5
* All the corrections needed in AndroidManifest.xml

the only way that I found to fix this is using version 1.1.2 of this package any other superior of this version will give me the same error.

(this is the first time I write an issue, tell me if you need more info hehe)

**Comment by ThexXTURBOXx** [comment]
I am reasonably sure that this is not an issue with this package as there has been no change in platform-specific code in version 2.0.0: https://github.com/ThexXTURBOXx/flutter_web_auth_2/compare/1.1.2...2.0.0
The error `Unsupported class file major version 61` [indicates that](https://stackoverflow.com/q/9170832/5894824) you are indeed not using Java 18, but something which is <= 16.
If you need further help with any of this, GitHub issues are not the right place, but you should rather at StackOverflow or similar
