### ISSUE TITLE
Macos (MissingPluginException(No implementation found for method cleanUpDanglingCalls)

### ISSUE THREAD

**Issue by zezo357** [ThexXTURBOXx/flutter_web_auth_2#78]
## Describe the bug
the auth on macos works but keeps throwing this error, but i was able to complete the process and i was able to authenticate
```
[EXCEPTION] | 20:0:50 929ms | Unhandled Exception
MissingPluginException(No implementation found for method cleanUpDanglingCalls on channel flutter_web_auth_2)
StackTrace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      FlutterWebAuth2._cleanUpDanglingCalls (package:flutter_web_auth_2/flutter_web_auth_2.dart:87:5)
<asynchronous suspension>
}
```
## Device 
 - Device: laptop
 - OS: Macos 14.0 (23A344)
 - Browser: Chrome
 - flutter_web_auth_2: ^3.0.1

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [x] I have provided all the information I can (incl. auth URL etc.)

**Comment by zezo357** [comment]
i am very sorry, this was due to me not recompiling the app after upgrading from version 2

**Comment by ThexXTURBOXx** [comment]
I was in the midst of typing a response when you figured out what's wrong. Thanks for keeping me updated! :)
Since this seems to be a very common issue, I will add `flutter clean` as a general troubleshooting step to the guide, though!
