### ISSUE TITLE
Platform dosnt init to Web when deployed to AWS

### ISSUE THREAD

**Issue by TheRealNOIG** [ThexXTURBOXx/flutter_web_auth_2#82]
## Describe the bug
Package dosnt initialize properly when deployed to AWS Static site.
When running localy on Web there are no issue but when deployed to AWS I receive this error

```MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)```

I resolved this issue by changing the default from windows to web but this probably isnt a good long term solutions

[https://github.com/TheRealNOIG/flutter_web_auth_2/commit/633e2068c244347d641afd63216f9ca224e9012d](https://github.com/TheRealNOIG/flutter_web_auth_2/commit/633e2068c244347d641afd63216f9ca224e9012d)

## To Reproduce
1. Build Flutter App to web
2. upload to AWS Static Site (I use SST for this)
3. Have something call FlutterWebAuth2.authenticate
4. Look at console for error ```MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)```

## Expected behavior
Open 3rd party auth site

## Device (please complete the following information!)
 - Browser: Chrome, Firefox, Edge
 - `flutter_web_auth_2` version: All version (tested from 2.2.1 to 3.0.2

## Checklist
 - [x] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
 - [X] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
I hope that this is now fixed in `3.0.3`. Could you please try and report back?
Conditional exporting seems to not work very nicely in Flutter/Dart yet, so I am guessing that 31d59aca8e3b438fa9b8afb287e5baf6a1c6a4a7 should do the trick :)

**Comment by TheRealNOIG** [comment]
That resolved it.
Thanks

**Comment by ThexXTURBOXx** [comment]
Perfect, thanks for reporting back!
