### ISSUE TITLE
On response, return the whole request instead of returning only the url

### ISSUE THREAD

**Issue by MohamadTahir** [ThexXTURBOXx/flutter_web_auth_2#85]
## Is your feature request related to a problem? Please describe.
in our implementation we are returning a cookie that I need to perform some tasks, currently, this is not possible.

## Describe the solution you'd like
I want to receive the whole response with the headers and everything.

**Comment by ThexXTURBOXx** [comment]
Thanks for the feature request!
However, using the current architecture, it is impossible to return the entire response.
I also don't think there is a nice way to do this cross-platform.
I will close this as not planned
