### ISSUE TITLE
Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [ThexXTURBOXx/flutter_web_auth_2#97]
The short version:
  - Migrate usage of dart:html to package:web
  - Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will also compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

**Comment by IchordeDionysos** [comment]
@ThexXTURBOXx this would also be a nice addition to the version 4.0.0 😌

**Comment by ThexXTURBOXx** [comment]
Thank you for reminding me. That was the last thing I wanted to do for 4.0.0, but I could not remember it. Will migrate in a minute :)

**Comment by ThexXTURBOXx** [comment]
Done in `4.0.0-alpha.2`!
